- name: create ec2 and r53 records
  hosts: localhost
  vars:
    zone: daws78s.online
    instances:
    - db
    - backend
    - frontend
tasks:
- name: creating ec2 instances
  amazon.aws.ec2_instance:
    instance type: t2.micro
    name: "{{item}}"
    security_group: allow-everything
    image_id: ami-090252cbe067a9e58
    tags:
      Name: "{{item}}"
  loop: "{{ instances }}"
  register: ec2_instances_info  

- name: print output
  ansible.builtin.debug:
    msg: "Output: {{ ec2_instances_info }}"    


